project:
  type: website
  output-dir: docs

website:
  title: "AMSA 2025-2026"
  navbar:
    left:
      - text: "ğŸ“ Slides"
        menu:
        - href: weeks/week-0.qmd
          text: "Week 0"
        - href: weeks/week-1.qmd
          text: "Week 1"
      - text: "ğŸ“š Activites"
        menu:
        - href: activities/act-1.qmd
          text: "Activity 1"

title: "AMSA"

author:
  - name: Ferran Aran Domingo
    email: ferran.aran@udl.cat
  - name: Francesc Solsona TehÃ s
    email: francesc.solsona@udl.cat
  - name: Oriol Agost Batalla
    email: oriol.agost@udl.cat
  - name: Pablo Fraile Alonso
    email: pablo.fraile@udl.cat

format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: true 
    transition: fade
    toc: true
    toc-depth: 1
    chalkboard: true
  html:
    theme: sketchy
    css: styles.css

editor: visual

execute:
  freeze: auto
  echo: true

mermaid:
      theme: neutral

logo: "logo.png"
favicon: "favicon.png"

footer: AMSA 2025-2026  -  [ğŸ  Home](/index.html)
